export const LIST_PRODUCT = "LIST_PRODUCT";
export const BUY_ITEM = "BUY_ITEM";
export const UPDATE_CARTITEM = "UPDATE_CARTITEM";
export const REMOVE_CARTITEM = "REMOVE_CARTITEM";
export const CHANGE_NOTIFY = "CHANGE_NOTIFY";
